---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management-app
  namespace: default
  labels:
    app: order-management-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-management-app
  template:
    metadata:
      labels:
        app: order-management-app
    spec:
      containers:
      - name: order-management-app
        image: "devopshint/order-managementapp-1.0:latest"
        ports:
          - containerPort: 8001


---
apiVersion: v1
kind: Service
metadata:
  name: order-management-app
  namespace: default
spec:
  selector:
    app: order-management-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 8001
    port: 8001